services:
  mongodb:
    image: mongo:latest
    container_name: logistrack-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=logistrack
    networks:
      - logistrack-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logistrack-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/logistrack
      - NODE_ENV=production
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    networks:
      - logistrack-network

volumes:
  mongodb_data:
    name: logistrack-mongodb-data

networks:
  logistrack-network:
    driver: bridge
